app/home/forms.py
from flask_wtf import FlaskForm, Form
from wtforms import StringField, PasswordField, FileField, IntegerField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo

class Register(FlaskForm):
    user_name = StringField(
        label='用户名称',
        validators=[DataRequired(message='用户名不能为空'),
                    Length(min=3, max=15, message='用户名长度在3到15个字符之间')],
        render_kw={'id': 'user_name', 'class': 'form-control', 'placeholder': '请输入用户名', 'required': 'reqiured'})
    user_pwd = PasswordField(
        label='用户密码',
        validators=[DataRequired(message='密码不能为空'),
                    Length(min=3, max=15, message='用户密码长度在3到15个字符之间')],
        render_kw={'id': 'user_pwd', 'class': 'form-control', 'placeholder': '请输入密码', 'required': 'reqiured'})
    user_confirm = PasswordField(
        label='确认密码',
        validators=[EqualTo('password', message='两次密码不一致')],
        render_kw={'id': 'user_pwd', 'class': 'form-control', 'placeholder': '请输入密码', 'required': 'reqiured'})
    user_email = StringField(
        label='用户邮箱',
        validators=[DataRequired(message='邮箱不能为空'),
                    Email(message='邮箱格式不正确')],
        render_kw={'id': 'user_email', 'class': 'form-control', 'placeholder': '请输入邮箱', 'required': 'reqiured'})
    user_phone = StringField(
        label='用户电话',
        validators=[DataRequired(message='用户电话不能为空'),
                    Length(min=3, max=15, message='用户名长度在3到15个字符之间')],
        render_kw={'id': 'user_name', 'class': 'form-control', 'placeholder': '请输入电话', 'required': 'reqiured'})
    # user_birthday = IntegerField(
    #     label='用户生日',
    #     validators=[DataRequired(message='用户生日不能为空')],
    #     render_kw={'id': 'user_birthday', 'class': 'form-control', 'placeholder': '请输入生日'})
    # user_face = FileField(
    #     label='用户头像',
    #     validators=[],
    #     render_kw={'id': 'user_face', 'class': 'form-control'})
    submit = SubmitField(
        render_kw={'value': '注册', 'class': 'form-control'})

class Login(FlaskForm):
    account = StringField(
        label='用户名称',
        validators=[DataRequired(message='用户名不能为空'),
                    Length(min=3, max=15, message='用户名长度在3到15个字符之间')],
        render_kw={'id': 'user_name', 'class': 'form-control', 'placeholder': '请输入用户名', 'required': 'reqiured'})
    pwd = PasswordField(
        label='用户密码',
        validators=[DataRequired(message='密码不能为空'),
                    Length(min=3, max=15, message='用户密码长度在3到15个字符之间')],
        render_kw={'id': 'user_pwd', 'class': 'form-control', 'placeholder': '请输入密码', 'required': 'reqiured'})
    submit = SubmitField(
        render_kw={'value': '登陆', 'class': 'form-control'})

class Changepwd(FlaskForm):
    pwd = PasswordField(
        label='用户密码',
        validators=[DataRequired(message='密码不能为空'),
                    Length(min=3, max=15, message='用户密码长度在3到15个字符之间')],
        render_kw={'id': 'user_pwd', 'class': 'form-control', 'placeholder': '请输入密码', 'required': 'reqiured'})
    submit = SubmitField(
        render_kw={'value': '登陆', 'class': 'form-control'})

class AddBlog(FlaskForm):
    title = StringField(
        label='文章标题',
        validators=[DataRequired(message='文章标题不能为空'),
                    Length(min=1, max=72, message='用户名长度在1到72个字符之间')],
        render_kw={'id': 'blog_tilte', 'class': 'form-control collapsed', 'placeholder': '请输入文章标题', 'required': 'reqiured'})
    info = StringField(
        label='文章标题',
        validators=[DataRequired(message='简介'),
                    Length(max=100, message='简介在一百字以内')],
        render_kw={'id': 'blog_info', 'class': 'form-control collapsed', 'placeholder': '请输入简介', 'required': 'reqiured'})
    text = TextAreaField(label='文章正文',
        validators=[DataRequired(message='正文'),
                    Length(min=1, message='正文不能为空')],
        render_kw={'id': 'blog_text', 'class': 'form-control collapsed', 'placeholder': '请输入正文', 'required': 'reqiured'})
    submit = SubmitField(
        render_kw={'value': '添加文章', 'class': 'form-control'})

# class PostForm(Form):
#     """Post Form."""
#
#     title = StringField('Title', [DataRequired(), Length(max=255)])
#     text = TextAreaField('Blog Content', [DataRequired()])

app/home/__init__.py
from flask import Blueprint
home = Blueprint('home', __name__)

import app.home.views
import sys
sys.setrecursionlimit(2000)

app/home/views.py
from . import home
from flask import render_template, redirect, url_for, request, session, flash
from .forms import Register, Login, AddBlog
from app.models import User, Comment, Blog, Userlog
from functools import wraps
from app import db

def user_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if session.get('account') == None:
            return redirect(url_for('home.login'))
        return f(*args, **kwargs)
    return decorated_function


# @admin.route('/')
# def inherit_html():
#     return render_template('admin/inherit_html.html')
# @user_login_req

@home.route('/')
def index():
    return render_template('home/blog.html')


@home.route('/blog')
def blog():
    blogs = Blog.query.all()
    return render_template('home/blog.html', blogs=blogs)


@home.route('/login', methods=['GET', 'POST'])
def login():
    form = Login()
    if request.method == "POST":
        account = request.form.get('account')
        pwd = request.form.get('pwd')
        user = User.query.filter_by(name=account).all()
        for i in user:
            if account != i.name:
                flash(u'用户不存在 ')
            elif pwd != i.pwd:
                flash(u'密码不正确')
            else:
                session['account'] = account
                return redirect(url_for('home.user_center'))
    return render_template('home/login.html', form=form)


@home.route('/register', methods=['GET', 'POST'])
def register():
    form = Register()
    if request.method == 'POST':
        user_name = request.form.get('user_name')
        user_pwd = request.form.get('user_pwd')
        user_email = request.form.get('user_email')
        user_phone = request.form.get('user_phone')
        user = User(name=user_name, pwd=user_pwd, email=user_email, phone=user_phone)
        db.session.add(user)
        db.session.commit()
        flash('添加成功')
        session['account'] = user_name
        return render_template('home/user_center.html')
    return render_template('home/register.html', form=form)


@home.route('/logout')
@user_login_req
def logout():
    session.pop('account')
    return render_template('home/logout.html')


@home.route('/center')
@user_login_req
def user_center():
    users = User.query.filter_by(name=session.get('account')).all()
    return render_template('home/user_center.html', users=users)


@home.route('/changepwd')
@user_login_req
def changepwd():
    users = User.query.filter_by(name=session.get('account')).all()
    return render_template('home/changepwd.html', users=users)


@home.route('/comment')
@user_login_req
def comment():
    users = User.query.filter_by(name=session.get('account')).all()
    for i in users:
        user_id = i.id
        comments = Comment.query.filter_by(user_id=user_id).all()
    return render_template('home/comment.html', users=users, comments=comments)


@home.route('/loginlog')
@user_login_req
def loginlog():
    users = User.query.filter_by(name=session.get('account')).all()
    for i in users:
        user_id = i.id
        user = session.get('account')
        user_log = Userlog(user_id=user_id)
        db.session.add(user_log)
        db.session.commit()
        userlog = Userlog.query.all()
    return render_template('home/loginlog.html', user=user, userlog=userlog)


@home.route('/collect')
@user_login_req
def collect():
    users = User.query.filter_by(name=session.get('account')).all()
    return render_template('home/collect.html', users=users)


@home.route('/about')
def about():
    return render_template('home/about.html')

@home.route('/add_blog', methods=['GET', 'POST'])
@user_login_req
def add_blog():
    form = AddBlog()
    if request.method == "POST":
        title = request.form.get('title')
        info = request.form.get('info')
        text = request.form.get('text')
        user = User.query.filter_by(name=session.get('account')).all()
        for i in user:
            blog = Blog(title=title, info=info, content=text, user_id=i.id)
            db.session.add(blog)
            db.session.commit()
            flash('添加成功')
    if form.error:
        flash('发表博客失败，请重试')
    return render_template('home/add_blog.html', form=form)

@home.route('/all_blog<int:blog_id>', methods=['GET', 'POST'])
def all_blog(blog_id):
    blogs = Blog.query.filter_by(id=blog_id).all()
    for blog in blogs:
        print(blog.content)
    return render_template('home/all_blog.html', blogs=blogs)




@home.route('/add_blog/', methods=['GET', 'POST'])
@user_login_req
def del_blog():
    return redirect(url_for('home.blog'))



@home.route('/add_blog', methods=['GET', 'POST'])
@user_login_req
def change_blog():
    pass

# @admin.route('/edit-articles/<int:id>', methods=['GET', 'POST'])
# @login_required
# def editArticles(id):
#     article = Article.query.get_or_404(id)
#     form = SubmitArticlesForm()
#
#     sources = [(s.id, s.name) for s in Source.query.all()]
#     form.source.choices = sources
#     types = [(t.id, t.name) for t in ArticleType.query.all()]
#     form.types.choices = types
#
#     if form.validate_on_submit():
#         articleType = ArticleType.query.get_or_404(int(form.types.data))
#         article.articleType = articleType
#         source = Source.query.get_or_404(int(form.source.data))
#         article.source = source
#
#         article.title = form.title.data
#         article.content = form.content.data
#         article.summary = form.summary.data
#         article.update_time = datetime.utcnow()
#         db.session.add(article)
#         db.session.commit()
#         flash(u'博文更新成功！', 'success')
#         return redirect(url_for('main.articleDetails', id=article.id))
#     form.source.data = article.source_id
#     form.title.data = article.title
#     form.content.data = article.content
#     form.types.data = article.articleType_id
#     form.summary.data = article.summary
#     return render_template('admin/submit_articles.html', form=form

app/templates/home/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

{#    <!-- <link href="../../../static/css/bootstrap.min.css" rel="stylesheet"> -->#}
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
        <link src="{{ url_for('static', filename='js/bootstrap.min.js') }}" rel="stylesheet">
        <link src="{{ url_for('static', filename='js/bootstrap.min.js') }}" rel="stylesheet">
    <title>flask博客</title>
</head>
<body>

<div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('home.blog') }}">dq博客</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="{{ url_for('home.blog') }}">首页</a></li>
              <li><a href="{{ url_for('home.blog') }}">我的博客</a></li>
              <li><a href="{{ url_for('home.about') }}">关于</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="{{ url_for('home.user_center') }}">个人中心 <span class="sr-only">(current)</span></a></li>
              <li><a href="{{ url_for('home.login') }}">登陆</a></li>
              <li><a href="{{ url_for('home.register') }}">注册</a></li>
              <li><a href="{{ url_for('home.index') }}">退出</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

{% block content %}

{% endblock %}

    </div > <!-- /container -->
<div class=" col-sm-9 col-md-3"></div>
<div class="jumbotron col-sm-9 col-md-5"><p>Hello，这是《Flask Web开发实战》第8章配套程序Bluelog的在线Demo，请访问helloflask.com/book了解更多信息。请注意，网站数据不会永久保存，网站也可能随时会关闭。另外，在线Demo中某些功能没有开放，请在本地运行项目体验完整功能。这个程序的源码可以在GitHub上获取。

如果你想让这个示例程序持续运行，可以考虑买一本《Flask Web开发实战》，或是通过其他方式支持我。

你可以在HelloFlask.com看到更多Flask程序。</p></div>

</body>
</html>

app/templates/home/add_blog.html
{% extends '/home/index.html' %}

{% block content %}
    <h2 class="col-md-offset-5">添加博客</h2>
    <form method="POST"  >
    <div style="color: red">{% for message in get_flashed_messages() %}
        {{ message }}
    {% endfor %}
    {% for e in form.title.errors %}
          <p class="help-block">{{ e }}</p>
    {% endfor %}
    </div>
    <div class="form-group has-feedback">
        {{ form.title.label }}{{ form.title }}
    </div>
        {% for e in form.info.errors %}
          <p class="help-block">{{ e }}</p>
    {% endfor %}
    <div class="form-group has-feedback">
        {{ form.info.label }}{{ form.info }}
    </div>
        {% for e in form.text.errors %}
          <p class="help-block">{{ e }}</p>
    {% endfor %}
    <div class="form-group has-feedback">
        {{ form.text.label }}{{ form.text }}
    </div>
    <div class="form-group has-feedback">
        {{ form.submit }}
    </div>
    </form>


{% endblock %}
{% block js %}
{#<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>#}
{#<script>#}
{#    CKEDITOR.replace('editor');#}
{#</script>#}
{% endblock %}

app/templates/home/all_blog.html
{% extends '/home/index.html' %}

{% block content %}

<div class="jumbotron" style="font-size: 40px">
       {% for blog in blogs %}
           <ul>作者id：{{ blog.user_id }}</ul>
           <ul>博客标题：{{ blog.title }}</ul>
           <ul>简介：{{ blog.info }}</ul>
           <ul>正文：{{ blog.content }}</ul>

       {% endfor %}
</div>




{% endblock %}

app/templates/home/changepwd.html
{% extends "/home/index.html" %}
{% block content %}
    {% include '/home/menu.html' %}
<div class="jumbotron col-md-9" style="padding: 10px 20%">
    <h2>changepwd</h2>
</div>


{% endblock %}
{% block js %}
    <script>
        $(document).ready(function () {
            $("#m-2").addClass('active')
        })
    </script>
{% endblock %}

app/templates/home/collect.html
{% extends "/home/index.html" %}

{% block content %}
    {% include '/home/menu.html' %}
    <div class="jumbotron col-md-9" style="padding: 10px 20%">
    <h2>collect</h2>
</div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            $("#m-5").addClass('active')
        })
    </script>
{% endblock %}

app/templates/home/comment.html
{% extends "/home/index.html" %}

{% block content %}
    {% include '/home/menu.html' %}
    <div class="jumbotron col-md-9" style="padding: 10px 20%">
        <h2>评论</h2>
    </div>

    <div class="col-md-9">
    {% for i in range(4) %}
        {% for comment in comments %}
            {% for user in users %}
            <ul> 用户：{{ user.name }} 评论：{{ comment.content }}</ul>
            {% endfor %}
        {% endfor %}
    {% endfor %}
    </div>
    {% endblock %}







{% block js %}
    <script>
        $(document).ready(function () {
            $("#m-3").addClass('active')
        })
    </script>
{% endblock %}

app/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">


        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
        <link src="{{ url_for('static', filename='js/bootstrap.min.js') }}" rel="stylesheet">
        <link src="{{ url_for('static', filename='js/bootstrap.min.js') }}" rel="stylesheet">
    <title>flask博客</title>
</head>
<body>

<div class="container">


      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('home.blog') }}">dq博客</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="{{ url_for('home.blog') }}">首页</a></li>
              <li><a href="{{ url_for('home.blog') }}">我的博客</a></li>
              <li><a href="{{ url_for('home.about') }}">关于</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="{{ url_for('home.user_center') }}">个人中心 <span class="sr-only">(current)</span></a></li>
              <li><a href="{{ url_for('home.login') }}">登陆</a></li>
              <li><a href="{{ url_for('home.register') }}">注册</a></li>
              <li><a href="{{ url_for('home.blog') }}">退出</a></li>
            </ul>
          </div>
        </div>
      </nav>

{% block content %}

{% endblock %}

    </div>
{% block js %}

{% endblock %}
</body>
</html>

app/templates/home/login.html
{% extends "/home/index.html" %}

{% block content %}
    {% include '/home/menu.html' %}
    <form method="POST"  class="col-md-3 col-md-offset-1 navbar-brand" style="color: #1b6d85">
    <div style="color: red">{% for message in get_flashed_messages() %}
        {{ message }}
    {% endfor %}</div>

    <h2 class="col-md-offset-1">用户登录界面</h2>

    <div class="form-group has-feedback">
        {{ form.account.label }}{{ form.account }}
        </div>
    <div class="form-group has-feedback">
        {{ form.pwd.label }}{{ form.pwd }}
        </div>
    <div class="form-group has-feedback">
        {{ form.submit }}
        </div>
    </form>
{% endblock %}

app/templates/home/loginlog.html
{% extends "/home/index.html" %}


{% block content %}
    {% include '/home/menu.html' %}
    <div class="jumbotron col-md-9" style="padding: 10px 20% " >
        <h2>登陆日志</h2>
    </div>

    <div class="col-md-9">
        {% for log in userlog %}
            <ul> 用户：{{ user }} 登陆日志：{{ log.addtion }}{{ userlog.addtion }}</ul>
        {% endfor %}
    </div>

{% endblock %}


{% block js %}
    <script>
        $(document).ready(function () {
            $("#m-5").addClass('active')
        })
    </script>
{% endblock %}

app/templates/home/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>logout</title>
</head>
<body>

</body>
</html>

app/templates/home/menu.html
<div class="col-lg-3">
    <div class="list-group">
        <li class="list-group-item m-1"><a href="{{ url_for('home.user_center') }}"><span class="glyphicon glyphicon-user">会员中心</span></a></li>
        <li class="list-group-item m-2"><a href="{{ url_for('home.changepwd') }}"><span class="glyphicon glyphicon-lock">修改密码</span></a></li>
        <li class="list-group-item m-3"><a href="{{ url_for('home.comment') }}"><span class="glyphicon glyphicon-comment">评论记录</span></a></li>
        <li class="list-group-item m-4"><a href="{{ url_for('home.loginlog') }}"><span class="glyphicon glyphicon-calendar">登陆日志</span></a></li>
        <li class="list-group-item m-5"><a href="{{ url_for('home.collect') }}"><span class="glyphicon glyphicon-header">收藏中心</span></a></li>
    </div>
</div>

app/templates/home/register.html
{% extends "/home/index.html" %}

{% block content %}
    {% include '/home/menu.html' %}
    <form method="POST"  class="col-md-3 col-md-offset-1 navbar-brand" style="color: #1b6d85">
    <div style="color: red">{% for message in get_flashed_messages() %}
        {{ message }}
    {% endfor %}</div>

    <h2 class="col-md-offset-1">用户注册界面</h2>

    <div class="form-group has-feedback">
        {{ form.user_name.label }}{{ form.user_name }}
        </div>
    <div class="form-group has-feedback">
        {{ form.user_pwd.label }}{{ form.user_pwd }}
        </div>
    <div class="form-group has-feedback">
        {{ form.user_confirm.label }}{{ form.user_confirm }}
        </div>
    <div class="form-group has-feedback">
        {{ form.user_email.label }}{{ form.user_email }}
        </div>
    <div class="form-group has-feedback">
        {{ form.user_phone.label }}{{ form.user_phone }}
        </div>
{#    <div class="form-group has-feedback">#}
{#        {{ form.user_face.label }}{{ form.user_face }}#}
{#        </div>#}
    <div class="form-group has-feedback">
        {{ form.submit }}
        </div>
    </form>
{% endblock %}

app/templates/home/user_center.html
{% extends "/home/index.html" %}

{% block content %}
    {% include '/home/menu.html' %}
    <div class="jumbotron col-md-9" style="padding: 10px 20%">
        <h2>{{ user }}</h2>
    {% for user in users %}
       <ul> 用户：{{ user.name }} 电话：{{ user.phone }} 邮箱：{{ user.email }}</ul>
    {% endfor %}

    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            $("#m-1").addClass('active')
        })
    </script>
{% endblock %}